site_name: Angela Ferguson – Technical Writer
site_url: https://flawlesswords.com
theme:
  name: material
  palette:
    primary: blue grey
    accent: deep purple
nav:
  - Home: index.md
  - Blog: 
    - Blog Home: blog/index.md
    - Vibecoding with Docs as Code: blog/Vibecoding with Docs as Code.md
strict: true

plugins:
  - search
  - blog
  